# Generated by Django 5.2.4 on 2025-07-04 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=100, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, help_text='Введите описание', max_length=100, null=True, verbose_name='Описание курса')),
                ('png', models.ImageField(blank=True, help_text='Добавьте превью', null=True, upload_to='Ims/png', verbose_name='Превью курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['name', 'description', 'png'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=100, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, help_text='Введите описание', max_length=100, null=True, verbose_name='Описание урока')),
                ('png', models.ImageField(blank=True, help_text='Добавьте картинку', null=True, upload_to='Ims/png', verbose_name='Превью урока')),
                ('link', models.TextField(blank=True, help_text='Введите ссылку', max_length=100, null=True, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(blank=True, help_text='Прикрепите урок к курсу', max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ims.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['name', 'course', 'description', 'png', 'link'],
            },
        ),
    ]
