# Generated by Django 5.2.4 on 2025-07-06 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ims', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('payment_amount', models.PositiveIntegerField(blank=True, help_text='Укажите сумма оплаты', null=True, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет')], help_text='Укажите способ оплаты', max_length=20, null=True, verbose_name='Способ оплаты')),
                ('paid_course', models.ForeignKey(blank=True, help_text='Выберите оплаченный курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ims.course', verbose_name='Оплаченный курс')),
                ('paid_lesson', models.ForeignKey(blank=True, help_text='Выберите оплаченный урок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ims.lesson', verbose_name='Оплаченный урок')),
                ('user_name', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
